language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script:
  - ajv compile -s public/schema.json
  - npm run build
  - npm test -- --coverage
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
addons:
  sonarcloud:
    organization: iomega
