version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: iomega/podp-api
    volumes:
      - ./data:/data
    environment:
       SHARED_TOKEN: ${SHARED_TOKEN:-ashdfjhasdlkjfhalksdjhflak}
       REDIS_URL: redis://redis:6379
       ZENODO_ACCESS_TOKEN: ${ZENODO_ACCESS_TOKEN}
       ZENODO_DEPOSITION_ID: ${ZENODO_DEPOSITION_ID}
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  app:
    build: app
    image: "iomega/paired-data-form"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - api
    ports:
      - "${PORT:-8443}:80"
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  redis:
