version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: iomega/podp-api
    restart: always
    volumes:
      - ./data:/data
    environment:
       SHARED_TOKEN: ${SHAREDTOKEN:-ashdfjhasdlkjfhalksdjhflak}
       REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  app:
    build: app
    image: "iomega/paired-data-form"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "${PORT:-8443}:80"
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  redis:
